[package]
name = "albert"
version = "0.1.7"
edition = "2021"
description = "A terminal calculator written in Rust with ❤️"
license = "Apache-2.0"

[dependencies]

[[bin]]
name = "al"
path = "src/main.rs"
